topics:
  - bitcoin
  - cryptocurrency
  - trading-bot
  - technical-analysis
  - github-actions
  - automation
  - crypto-trading
  - bitcoin-price
  - trading-signals
  - market-analysis
  - python-script
  - binance-api
  - sendgrid
  - trading-alerts
  - crypto-alerts
  - bitcoin-tracker
  - technical-indicators
  - moving-averages
  - stochastic-oscillator
  - rsi-indicator
  - trading-automation
  - crypto-monitoring
  - price-alerts
  - market-tracking
  - defi
